/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionResult } from '../../models/action-result';

export interface VersionStoresUpdateStorePut$Plain$Params {
  version: string;
  clientId: string;
  sessionId: string;
  storeId: string;
  newStoreBranch?: string;
  newStoreAddress?: string;
}

export function versionStoresUpdateStorePut$Plain(http: HttpClient, rootUrl: string, params: VersionStoresUpdateStorePut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
  const rb = new RequestBuilder(rootUrl, versionStoresUpdateStorePut$Plain.PATH, 'put');
  if (params) {
    rb.path('version', params.version, {});
    rb.query('clientId', params.clientId, {});
    rb.query('sessionId', params.sessionId, {});
    rb.query('storeId', params.storeId, {});
    rb.query('newStoreBranch', params.newStoreBranch, {});
    rb.query('newStoreAddress', params.newStoreAddress, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResult>;
    })
  );
}

versionStoresUpdateStorePut$Plain.PATH = '/{version}/Stores/UpdateStore';
