/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionResult } from '../../models/action-result';

export interface VersionStoresAddStorePost$Plain$Params {
  version: string;
  clientId: string;
  sessionId: string;
  storeBranch: string;
  storeAddress: string;
}

export function versionStoresAddStorePost$Plain(http: HttpClient, rootUrl: string, params: VersionStoresAddStorePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
  const rb = new RequestBuilder(rootUrl, versionStoresAddStorePost$Plain.PATH, 'post');
  if (params) {
    rb.path('version', params.version, {});
    rb.query('clientId', params.clientId, {});
    rb.query('sessionId', params.sessionId, {});
    rb.query('storeBranch', params.storeBranch, {});
    rb.query('storeAddress', params.storeAddress, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResult>;
    })
  );
}

versionStoresAddStorePost$Plain.PATH = '/{version}/Stores/AddStore';
