/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionResult } from '../../models/action-result';

export interface VersionItemsUpdateItemPut$Plain$Params {
  version: string;
  clientId: string;
  sessionId: string;
  itemId: string;
  itemCode?: string;
  itemDescription?: string;
  itemPrice?: number;
  itemStock?: number;
      body?: {
'itemImg'?: Blob;
}
}

export function versionItemsUpdateItemPut$Plain(http: HttpClient, rootUrl: string, params: VersionItemsUpdateItemPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
  const rb = new RequestBuilder(rootUrl, versionItemsUpdateItemPut$Plain.PATH, 'put');
  if (params) {
    rb.path('version', params.version, {});
    rb.query('clientId', params.clientId, {});
    rb.query('sessionId', params.sessionId, {});
    rb.query('itemId', params.itemId, {});
    rb.query('itemCode', params.itemCode, {});
    rb.query('itemDescription', params.itemDescription, {});
    rb.query('itemPrice', params.itemPrice, {});
    rb.query('itemStock', params.itemStock, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResult>;
    })
  );
}

versionItemsUpdateItemPut$Plain.PATH = '/{version}/Items/UpdateItem';
