/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionResult } from '../../models/action-result';

export interface VersionItemsClientAddItemPost$Json$Params {
  version: string;
  clientId: string;
  sessionId: string;
  itemID: string;
  itemAmount: number;
  operationDate: string;
}

export function versionItemsClientAddItemPost$Json(http: HttpClient, rootUrl: string, params: VersionItemsClientAddItemPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
  const rb = new RequestBuilder(rootUrl, versionItemsClientAddItemPost$Json.PATH, 'post');
  if (params) {
    rb.path('version', params.version, {});
    rb.query('clientId', params.clientId, {});
    rb.query('sessionId', params.sessionId, {});
    rb.query('itemID', params.itemID, {});
    rb.query('itemAmount', params.itemAmount, {});
    rb.query('operationDate', params.operationDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResult>;
    })
  );
}

versionItemsClientAddItemPost$Json.PATH = '/{version}/ItemsClient/AddItem';
