/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionResult } from '../../models/action-result';

export interface VersionClientsAddClientPost$Json$Params {
  version: string;
  userName: string;
  password: string;
  clientName: string;
  clientLastName: string;
  clientAddress: string;
}

export function versionClientsAddClientPost$Json(http: HttpClient, rootUrl: string, params: VersionClientsAddClientPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
  const rb = new RequestBuilder(rootUrl, versionClientsAddClientPost$Json.PATH, 'post');
  if (params) {
    rb.path('version', params.version, {});
    rb.query('userName', params.userName, {});
    rb.query('password', params.password, {});
    rb.query('clientName', params.clientName, {});
    rb.query('clientLastName', params.clientLastName, {});
    rb.query('clientAddress', params.clientAddress, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResult>;
    })
  );
}

versionClientsAddClientPost$Json.PATH = '/{version}/Clients/AddClient';
