/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionResult } from '../../models/action-result';

export interface VersionClientsUpdateClientPut$Json$Params {
  version: string;
  clientId: string;
  sessionId: string;
  currentPassword: string;
  newPassword?: string;
  userName?: string;
  newClientName?: string;
  newClientLastName?: string;
  newClientAddress?: string;
}

export function versionClientsUpdateClientPut$Json(http: HttpClient, rootUrl: string, params: VersionClientsUpdateClientPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
  const rb = new RequestBuilder(rootUrl, versionClientsUpdateClientPut$Json.PATH, 'put');
  if (params) {
    rb.path('version', params.version, {});
    rb.query('clientId', params.clientId, {});
    rb.query('sessionId', params.sessionId, {});
    rb.query('currentPassword', params.currentPassword, {});
    rb.query('newPassword', params.newPassword, {});
    rb.query('userName', params.userName, {});
    rb.query('newClientName', params.newClientName, {});
    rb.query('newClientLastName', params.newClientLastName, {});
    rb.query('newClientAddress', params.newClientAddress, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResult>;
    })
  );
}

versionClientsUpdateClientPut$Json.PATH = '/{version}/Clients/UpdateClient';
